# .github/workflows/send_commit_email.yaml
name: Summarize & Email

on:
  workflow_call:
    inputs:
      openai_model:
        required: false
        type: string
        default: gpt-4o-mini
    secrets:
      OPENAI_API_KEY:
        required: true
      SMTP_USERNAME:
        required: true
      SMTP_PASSWORD:
        required: true
      CLIENT_EMAIL:
        required: true

jobs:
  send:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Summarize commits with OpenAI
        uses: Serbyte-Development/actions@v1
        id: summarize
        with:
          openai-model: ${{ inputs.openai_model }}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: E-mail client
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Website Update: New Changes Implemented - ${{ github.repository }}"
          to: ${{ secrets.CLIENT_EMAIL }}
          from: Serbyte Bot <${{ secrets.SMTP_USERNAME }}>
          html_body: ${{ steps.summarize.outputs.email_body }}
